# Numpy

![elgif](https://media.giphy.com/media/VHqZtsoHHPo58EL7Ua/giphy.gif)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#¿Qué-es-Numpy?" data-toc-modified-id="¿Qué-es-Numpy?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>¿Qué es Numpy?</a></span></li><li><span><a href="#Trabajar-con-datos-numéricos" data-toc-modified-id="Trabajar-con-datos-numéricos-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Trabajar con datos numéricos</a></span></li><li><span><a href="#Pasar-de-las-listas-de-Python-a-las-matrices-de-Numpy" data-toc-modified-id="Pasar-de-las-listas-de-Python-a-las-matrices-de-Numpy-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Pasar de las listas de Python a las matrices de Numpy</a></span></li><li><span><a href="#Operando-con-Numpy-Arrays" data-toc-modified-id="Operando-con-Numpy-Arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Operando con Numpy Arrays</a></span></li><li><span><a href="#Ventajas-del-uso-de-arrays-Numpy" data-toc-modified-id="Ventajas-del-uso-de-arrays-Numpy-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Ventajas del uso de arrays Numpy</a></span></li><li><span><a href="#Creamos-Arrays" data-toc-modified-id="Creamos-Arrays-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Creamos Arrays</a></span><ul class="toc-item"><li><span><a href="#Números-random" data-toc-modified-id="Números-random-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Números random</a></span></li><li><span><a href="#Arange" data-toc-modified-id="Arange-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Arange</a></span></li><li><span><a href="#Linespace" data-toc-modified-id="Linespace-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Linespace</a></span></li><li><span><a href="#Around" data-toc-modified-id="Around-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Around</a></span></li><li><span><a href="#Arrays-a-partir-de-datos" data-toc-modified-id="Arrays-a-partir-de-datos-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Arrays a partir de datos</a></span></li></ul></li><li><span><a href="#Retornamos-a-lista-un-numpy-array" data-toc-modified-id="Retornamos-a-lista-un-numpy-array-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Retornamos a lista un numpy array</a></span><ul class="toc-item"><li><span><a href="#Matriz-de-CEROS" data-toc-modified-id="Matriz-de-CEROS-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Matriz de CEROS</a></span></li><li><span><a href="#Matriz-de-UNOS" data-toc-modified-id="Matriz-de-UNOS-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Matriz de UNOS</a></span></li><li><span><a href="#Matriz-DIAGONAL" data-toc-modified-id="Matriz-DIAGONAL-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Matriz DIAGONAL</a></span></li></ul></li><li><span><a href="#Explorar-arrays-y-sus-propiedades" data-toc-modified-id="Explorar-arrays-y-sus-propiedades-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Explorar arrays y sus propiedades</a></span></li><li><span><a href="#Manipular-arrays" data-toc-modified-id="Manipular-arrays-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Manipular arrays</a></span></li><li><span><a href="#Comparación-de-arrays" data-toc-modified-id="Comparación-de-arrays-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Comparación de arrays</a></span></li><li><span><a href="#Array-indexing-and-slicing" data-toc-modified-id="Array-indexing-and-slicing-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Array indexing and slicing</a></span><ul class="toc-item"><li><span><a href="#Mezcla-de-índices-y-rangos" data-toc-modified-id="Mezcla-de-índices-y-rangos-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>Mezcla de índices y rangos</a></span></li></ul></li><li><span><a href="#Métodos-de-los-np.arrays" data-toc-modified-id="Métodos-de-los-np.arrays-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Métodos de los np.arrays</a></span><ul class="toc-item"><li><span><a href="#Métodos-de-Numpy-(los-vimos-el-lunes)" data-toc-modified-id="Métodos-de-Numpy-(los-vimos-el-lunes)-12.1"><span class="toc-item-num">12.1&nbsp;&nbsp;</span>Métodos de Numpy (los vimos el lunes)</a></span></li></ul></li><li><span><a href="#Cosas-divertidas-que-nos-permite-Numpy" data-toc-modified-id="Cosas-divertidas-que-nos-permite-Numpy-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Cosas divertidas que nos permite Numpy</a></span></li><li><span><a href="#Resumen" data-toc-modified-id="Resumen-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Resumen</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Further materials</a></span></li></ul></div>

## ¿Qué es Numpy?

NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas. El precursor de NumPy, Numeric, fue creado originalmente por Jim Hugunin con contribuciones de varios otros desarrolladores. En 2005, Travis Oliphant creó NumPy incorporando características de la competencia Numarray en Numeric, con amplias modificaciones. NumPy es un software de código abierto y cuenta con muchos colaboradores.

El núcleo del paquete NumPy es el objeto ndarray. Este encapsula matrices n-dimensionales de tipos de datos homogéneos, con muchas operaciones que se realizan en código compilado para el rendimiento. Hay varias diferencias importantes entre las matrices de NumPy y las secuencias estándar de Python:

![numpy](../images/numpy.png)

## Trabajar con datos numéricos    
Los "datos" en el análisis de datos suelen referirse a datos numéricos, por ejemplo, precios de las acciones, cifras de ventas, mediciones de sensores, resultados deportivos, tablas de bases de datos, etc. La biblioteca Numpy proporciona estructuras de datos especializadas, funciones y otras herramientas para la computación numérica en Python. Vamos a trabajar con un ejemplo para ver por qué y cómo utilizar Numpy para trabajar con datos numéricos.

Supongamos que queremos utilizar datos climáticos como la temperatura, la lluvia y la humedad para determinar si una región es adecuada para el cultivo de manzanas. Un enfoque sencillo para hacerlo sería formular la relación entre el rendimiento anual de las manzanas (toneladas por hectárea) y las condiciones climáticas como la temperatura media (en grados Fahrenheit), las precipitaciones (en milímetros) y la humedad relativa media (en porcentaje) como una ecuación lineal.

rendimiento_de_manzanas = w1 * temperatura + w2 * precipitaciones + w3 * humedad

Estamos expresando el rendimiento de las manzanas como una suma ponderada de la temperatura, las precipitaciones y la humedad. Esta ecuación es una aproximación, ya que la relación real no tiene por qué ser lineal y pueden intervenir otros factores. Pero un modelo lineal simple como éste suele funcionar bien en la práctica.

Basándonos en un análisis estadístico de los datos históricos, podemos obtener valores razonables para las ponderaciones w1, w2 y w3. He aquí un ejemplo de valores:

In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

<img src="../images/dat_np.png" alt="data" style="width:500px,"/>

In [2]:
temp = 73
lluvia = 67
humedad = 43

Ahora podemos sustituir estas variables en la ecuación lineal para predecir el rendimiento de las manzanas.

In [3]:
cultivo = temp * w1 + lluvia * w2 + humedad * w3 

In [4]:
print(f"El rendimiento de mis manzanas en la región de Kanto de es de {cultivo} toneladas por hectárea")

El rendimiento de mis manzanas en la región de Kanto de es de 56.8 toneladas por hectárea


Para facilitar un poco el cálculo anterior para varias regiones, podemos representar los datos climáticos de cada región como un vector, es decir, una lista de números.

In [5]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

Los tres números de cada vector representan los datos de temperatura, precipitación y humedad, respectivamente.
También podemos representar el conjunto de pesos utilizados en la fórmula como un vector.

In [6]:
pesos = [w1,w2,w3]

¿Cómo podemos hacer para calcular el cultivo de cada región?

In [7]:
kanto * pesos

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
def cultivo(region,pesos):
    resultado = 0
    for re,pe in zip(region,pesos):
        resultado += re * pe
    return resultado

In [8]:
def multi(a,b):
    return a * b

In [9]:
sum(list(map(multi,kanto,pesos)))

56.8

In [10]:
cultivo(kanto,pesos)

TypeError: 'float' object is not callable

In [11]:
cultivo(johto,pesos)

TypeError: 'float' object is not callable

¿Por qué lo hacemos así?

In [12]:
lista = [1,2,5,6,2,2,6]

In [13]:
lista * 3

[1, 2, 5, 6, 2, 2, 6, 1, 2, 5, 6, 2, 2, 6, 1, 2, 5, 6, 2, 2, 6]

## Pasar de las listas de Python a las matrices de Numpy   
El cálculo realizado por el crop_yield (multiplicación por elementos de dos vectores y tomar una suma de los resultados) también se llama producto punto. Para saber más sobre el producto punto, consulte: https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length .

La biblioteca Numpy proporciona una función integrada para calcular el producto punto de dos vectores. Sin embargo, primero debemos convertir las listas en matrices Numpy.

Instalemos la biblioteca Numpy usando el gestor de paquetes pip.

In [14]:
!pip install numpy

A continuación, vamos a importar el módulo numpy. Es una práctica común importar numpy con el alias np. Esto es una convención, todas las programadoras utilizamos los mismos nombres a la hora de importar las librerías. Realmente funciona si pongo cualquier nombre, en caso de numpy usamos siempre np

In [15]:
import numpy as np

Ahora podemos utilizar la función np.array para crear matrices Numpy.

In [16]:
kanto_np = np.array([73, 67, 43])

In [17]:
kanto_np

array([73, 67, 43])

In [18]:
print(kanto_np)

[73 67 43]


In [19]:
type(kanto_np)

numpy.ndarray

In [20]:
pesos_np = np.array(pesos)

In [21]:
pesos_np

array([0.3, 0.2, 0.5])

## Operando con Numpy Arrays

In [23]:
kanto_np * pesos_np

array([21.9, 13.4, 21.5])

In [24]:
sum(kanto_np*pesos_np)

56.8

In [25]:
# Vemos que cuando hay un array de numpy podemos multiplicarlo por una lista

In [28]:
kanto_np * [2,3,4]

array([146, 201, 172])

Ahora podemos calcular el producto punto de los dos vectores utilizando la función np.dot.

In [31]:
dot_np = np.dot(kanto_np, pesos_np)

In [32]:
dot_listas = np.dot(kanto,pesos)

In [33]:
type(dot_listas)

numpy.float64

Podemos conseguir el mismo resultado con operaciones de bajo nivel soportadas por las matrices Numpy: realizando una multiplicación por elementos y calculando la suma de los números resultantes.

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [35]:
arr1 * arr2

array([ 4, 10, 18])

El operador * realiza una multiplicación por elementos de dos matrices si tienen el mismo tamaño. El método sum calcula la suma de los números de una matriz.

## Ventajas del uso de arrays Numpy

Las matrices de Numpy ofrecen las siguientes ventajas sobre las listas de Python para operar con datos numéricos:

- Facilidad de uso: Puedes escribir expresiones matemáticas pequeñas, concisas e intuitivas como `(kanto * weights).sum()` en lugar de utilizar bucles y funciones personalizadas como cultivo().    
- Rendimiento: Las operaciones y funciones de Numpy se implementan internamente en C++, lo que las hace mucho más rápidas que el uso de sentencias y bucles de Python que se interpretan en tiempo de ejecución      
A continuación se muestra una comparación de los productos punto realizados con bucles de Python frente a matrices de Numpy en dos vectores con un millón de elementos cada uno.

In [52]:
# Listas de python de 0 a 1000000 y 1000000 a 2000000
arr1 = list(range(10000000))
arr2 = list(range(10000000,20000000))
# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

Comprobamos el tiempo de ejecución haciendo el producto punto con un bucle

In [53]:
import time

In [54]:
%time
total = 0
for x1,x2 in zip(arr1,arr2):
    total += x1 *x2
total

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 4.05 µs


833333233333335000000

Ahora con numpy

In [55]:
%time
np.dot(arr1_np, arr2_np)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.25 µs


3229750016405177280

In [56]:
%time
np.dot(arr1,arr2)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 3.81 µs


3229750016405177280

## Creamos Arrays
### Números random

In [58]:
# Vector (1 dimensión)
vector = np.random.random(7)
vector

array([0.8404378 , 0.25631178, 0.68808308, 0.79547712, 0.74419091,
       0.58925304, 0.52721398])

In [61]:
# 2 dimensiones random.random
matriz1 = np.random.random((3,4))
matriz1

array([[0.63808665, 0.37191501, 0.49556347, 0.56480444],
       [0.57862481, 0.24740961, 0.487801  , 0.99090012],
       [0.77314721, 0.64069229, 0.56471675, 0.78633233]])

In [72]:
# Matriz (2 Dimensiones)
a = np.random.randint(4, size=(3,4))
a

array([[3, 3, 1, 3],
       [3, 2, 0, 1],
       [0, 2, 3, 2]])

In [79]:
otro = np.random.randint(4,9, size=(3,4))
otro

array([[4, 6, 5, 5],
       [6, 6, 7, 5],
       [5, 7, 6, 6]])

In [80]:
# los parámetros dentro de random puedo pasarlos con nombre o sin ellos
b = np.random.randint(low=3, high=9, size=(3,4))
b

array([[4, 6, 4, 5],
       [8, 4, 8, 7],
       [6, 5, 7, 7]])

In [84]:
# Aquí lo paso sin nombre pero hace exactamente lo mismo 
otro_ = np.random.randint(40,100,(3,4))
otro_

array([[76, 77, 48, 76],
       [46, 78, 58, 68],
       [88, 99, 68, 67]])

[Random Randint](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) vs [Random Random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html)

In [85]:
type(otro_)

numpy.ndarray

In [87]:
# Cubo (3 dimensiones)
cubo = np.random.random((3,3,3))
cubo

array([[[0.27832545, 0.67017923, 0.3968107 ],
        [0.74832999, 0.80611104, 0.84452706],
        [0.09145786, 0.97014704, 0.09955221]],

       [[0.4547275 , 0.27399146, 0.16910969],
        [0.5118339 , 0.24899901, 0.66920391],
        [0.13724914, 0.64655407, 0.81539785]],

       [[0.73679618, 0.84657039, 0.77524169],
        [0.02186328, 0.8560129 , 0.67453202],
        [0.48240397, 0.12171241, 0.37380814]]])

In [92]:
# Tensor rango 4
tensor = np.random.random(size=(4,3,2,3)) # Dimensiones, bueno sin más tengo cuatro cubos 
tensor
"""
Cuatro cubos de 3 * 2 * 3
"""

'\nCuatro cubos de 3 * 2 * 3\n'

Numpy también proporciona algunas funciones útiles para crear matrices de formas deseadas con valores fijos o aleatorios.       
Consulta la [documentación](https://numpy.org/doc/stable/reference/routines.array-creation.html) oficial o utiliza la función de ayuda para obtener más información.

### Arange
Rango con inicio, fin y paso (start, stop, step)

In [93]:
# Rango entre 0 y 10 con saltos de 5
np.arange(0,11,5)

array([ 0,  5, 10])

### Linespace
La función NumPy linspace crea secuencias de valores espaciados uniformemente dentro de un intervalo definido.

Esencialmente, se especifica un punto inicial y un punto final de un intervalo, y luego se especifica el número total de puntos de ruptura que se desea dentro de ese intervalo (incluyendo los puntos inicial y final). La función np.linspace devolverá una secuencia de valores espaciados uniformemente en ese intervalo.

In [95]:
# 5 elementos que están entre 0 y 10 igualmente espaciados
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Around
Nos permite redondear los arrays a los decimales que le digamos 🙃 Gracias Silvia

In [100]:
np.around(np.linspace(0,10,20),2)

array([ 0.  ,  0.53,  1.05,  1.58,  2.11,  2.63,  3.16,  3.68,  4.21,
        4.74,  5.26,  5.79,  6.32,  6.84,  7.37,  7.89,  8.42,  8.95,
        9.47, 10.  ])

### Arrays a partir de datos

In [102]:
array1 = np.array([1,2,3,4,5,6])
array1

array([1, 2, 3, 4, 5, 6])

In [103]:
lista = [1,2,3,54]

In [104]:
np.array(lista)

array([ 1,  2,  3, 54])

In [105]:
b = np.array([[1,2,3], [1,5,7], [23,5,7]])

In [106]:
b

array([[ 1,  2,  3],
       [ 1,  5,  7],
       [23,  5,  7]])

In [107]:
type(b)

numpy.ndarray

## Retornamos a lista un numpy array

Cuando tengo un vector puedo utilizar .tolist o list(pongaaquísuarray)

In [120]:
tengounarray = np.array([1,2,3])

In [121]:
list(tengounarray)

[1, 2, 3]

In [110]:
alista = array1.tolist()
alista

[1, 2, 3, 4, 5, 6]

In [111]:
type(alista)

list

Si el array es de más de una dimensión ya no podremos hacerlo con list(array) porque tendremos una lista de arrays de numpy y no una lista de listas

In [122]:
b # esto es un array de numpy

array([[ 1,  2,  3],
       [ 1,  5,  7],
       [23,  5,  7]])

In [124]:
lista_arrays = list(b) # Si intento castear con python tengo una lista de arrays de numpy

In [126]:
type(lista_arrays[0])

numpy.ndarray

In [117]:
lista_grande = b.tolist()
lista_grande

[[1, 2, 3], [1, 5, 7], [23, 5, 7]]

In [116]:
type(lista_grande[0])

list

In [ ]:
type()

### Matriz de CEROS
Se utiliza np.zeros para crear el array de que todos los elementos son 0. Su sintaxis es:     
`np.zeros(shape, dtype=float, order='C')`

Dónde:    
- La shape es el tamaño del array, y puede ser 1-D, 2-D o múltiples dimensiones.
- El dtype es float64 por defecto, pero puede ser asignado con cualquier tipo de datos en NumPy.

In [ ]:
# Array 1D con 5 ceros


In [ ]:
# Array 1D con 5 ceros con tipo de datos "int8" (Valores de 64 bits)


In [ ]:
# Array 2D de 4x3 


### Matriz de UNOS
De forma similar a los zeros, también podríamos crear el array lleno de unos. La sintaxis y los parámetros de np.ones() son idénticos a los de np.zeros().

### Matriz DIAGONAL
Devuelve una matriz bidimensional con unos en la diagonal y ceros en el resto. La sintaxis es:     
`np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')`   
Dónde:         
- **N**: 	INT	Especifica el número de líneas en el array generada.
- **M**:	INT	(Opcional) El valor por defecto es None. Especifica el número de columnas en el array que se generará. Cuando es None, es igual a N.
- **k**:	INT	(Opcional) El valor por defecto es 0. 0 es la posición principal de la diagonal. Si k es positiva, crea la diagonal superior con el desplazamiento de k; si k es negativa, crea la diagonal inferior con el desplazamiento de k.
- **dtype**: tipo de datos	(Opcional) El valor por defecto es float. Especifica el tipo de datos del elemento del array creado.

In [ ]:
np.eye(4, k=-1)

## Explorar arrays y sus propiedades

In [ ]:
# Forma


In [ ]:
# Tamaño


In [ ]:
# Dimensiones


## Manipular arrays

In [ ]:
# Transponemos el array haciendo referencia a la posición anterior (RAS ESPECIFICA ESTO MÁS)


## Comparación de arrays

Las matrices Numpy también soportan operaciones de comparación como ==, !=, > etc. El resultado es un array de booleanos.

In [ ]:
# Arr_a y arr_b no tienen el mismo shape

La comparación de matrices se utiliza frecuentemente para contar el número de elementos iguales en dos matrices utilizando el método de la suma. Recuerde que Verdadero se evalúa como 1 y Falso se evalúa como 0 cuando se utilizan booleanos en operaciones aritméticas.

## Array indexing and slicing
Numpy extiende la notación de indexación de listas de Python utilizando [] a múltiples dimensiones de una manera intuitiva. Puedes proporcionar una lista de índices o rangos separados por comas para seleccionar un elemento específico o un subarray (también llamado slice) de un array de Numpy.

In [ ]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

Podemos escribir las posiciones directamente en una lista

### Mezcla de índices y rangos

## Métodos de los np.arrays

### Métodos de Numpy (los vimos el lunes)

¿Cómo los vemos? `dir(objeto)` muestra todos los métodos posibles que se pueden aplicar al objeto

In [ ]:
#dir(a

## Cosas divertidas que nos permite Numpy

Pillow! The Python Imaging Library adds image processing capabilities to your Python interpreter.   
[La doc 🙃](https://pillow.readthedocs.io/en/stable/)

¡¡Podemos procesar imágenes con Numpy!!

Una imagen digital se descompone en nuestro ordenador como un array de 3 dimensiones donde cada pixel es un valor de 0 a 255 siendo 0 negro y 255 blanco. 

## Resumen
Es tu turno ¿Qué hemos aprendido hoy?


## Further materials
- [NumPy Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
- [Master Numpy](https://medium.com/analytics-vidhya/master-numpy-in-45-minutes-74b2460ecb00)
- [Numpy Tricks](https://github.com/patidarparas13/Numpy-Tricks/blob/master/Numpy%2BTricks(Zero%2Bto%2BHero).ipynb)
[Procesado de Imágenes](https://claudiovz.github.io/scipy-lecture-notes-ES/advanced/image_processing/index.html)
- [101 Numpy exercises](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)
